django/0902/articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'
urlpatterns = [
    path('', views.index, name='index'),
    path('new/', views.new, name='new'),
    path('create/', views.create, name='create'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/edit/', views.edit, name='edit'),
    path('<int:pk>/update/', views.update, name='update'),
    # path(),
    # path(),
    # path(),
    # path(),
    # path(),
    # path(),
]

django/0902/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('articles/', include('articles.urls')),
    path('admin/', admin.site.urls),
]

django/0902/articles/models.py
from django.db import models

# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=20)                 # User input, Class variable
    content = models.TextField()                            # User input
    created_at = models.DateTimeField(auto_now_add=True)    # Auto-filled by django
    updated_at = models.DateTimeField(auto_now=True)        # Auto-filled by django

    def __str__(self):
        return f'Post #{self.pk}: {self.title}'

django/0902/articles/views.py
from django.http import request
from django.shortcuts import render, redirect
from .models import Article

# Create your views here.
def index(request):
    # articles = Article.objects.all()[::-1]  # order by python
    articles = Article.objects.order_by('-id')  # order by ORM
    context = {
        'articles': articles
    }

    return render(request, 'articles/index.html', context)

def new(request):

    return render(request, 'articles/new.html')

def create(request):
    print(request.POST) # GET: DB 쓰기 없음 / 민감하지 않은 정보 등
    title = request.POST.get('title')        # template의 name으로 넘어온 것
    content = request.POST.get('content')

    # article = Article()
    # article.title = title
    # article.content = content
    # article.save()

    # article = Article(title, content)

    article = Article(title=title, content=content)
    # Vaildation and Processing will be written here
    article.save()

    return redirect('articles:detail', article.pk)
    # return render(request, 'articles/create.html')

def detail(request, pk):                # variable routing
    article = Article.objects.get(pk=pk)
    context = {
        'article': article,
    }

    return render(request, 'articles/detail.html', context)

def delete(request, pk):
    article = Article.objects.get(pk=pk)
    if request.method == 'POST':
        article.delete()
        return redirect('articles:index')
    else:
        return redirect('articles:detail', article.pk)

def edit(request, pk):
    article = Article.objects.get(pk=pk)
    context = {
        'article': article,
    }
    return render(request, 'articles/edit.html', context)

def update(request, pk):
    article = Article.objects.get(pk=pk)
    article.title = request.POST.get('title')
    article.content = request.POST.get('content')
    article.save()

    return redirect('articles:detail', article.pk)

django/0902/articles/templates/articles/create.html
{% extends 'base.html' %}

{% block content %}
  <h1 class="text-center">Posting Success.</h1>
{% endblock content %}

django/0902/articles/templates/articles/detail.html
{% extends 'base.html' %}

{% block content %}
<h2 class="text-center">Detail</h2>
<p>Title: {{ article.title }}</p>
<p>Content: {{ article.content }}</p>
<p>Created at: {{ article.created_at }}</p>
<p>Updated at: {{ article.updated_at }}</p>
<hr>
<a href="{% url 'articles:edit' article.pk %}" class="btn btn-primary">Edit</a><br>

<form action="{% url 'articles:delete' article.pk %}" method="POST">
  {% csrf_token %}
  <button class="btn btn-danger">Delete</button>
</form>
<a href="{% url 'articles:index' %}">[Go to Main]</a>
{% endblock content %}

django/0902/articles/templates/articles/edit.html
{% extends 'base.html' %}
{% block content %}
<h1>EDIT</h1>

<form action="{% url 'articles:update' article.pk %}" method="POST">
  {% csrf_token %}
  <label for="title">TITLE: </label>
  <input type="text" id="title" name="title" value="{{ article.title }}"><br>
  <!-- form >> request >>  -->
  <label for="content">CONTENT: </label>
  <textarea name="content" id="content" cols="30" rows="10">{{ article.content }}</textarea><br>
  <input type="submit" value="작성">
</form>

<a href="{% url 'articles:index' %}">[메인 페이지로 이동]</a>
{% endblock content %}

django/0902/articles/templates/articles/index.html
{% extends 'base.html' %}

{% block content %}
  <h1 class="text-center">Articles의 index</h1>

  <a href="{% url 'articles:new' %}">[게시글 작성]</a>

  <br>

  {% for article in articles %}
    <p>Post number: {{ article.pk }}</p>
    <p>Post Title: {{ article.title }}</p>
    <p>Content: {{ article.content }}</p>
    <a href="{% url 'articles:detail' article.pk %}">[Go to Details]</a>
    <!-- variable routing할 값을 같이 넘겨주기 -->
    <hr>
  {% endfor %}

{% endblock content %}

django/0902/articles/templates/articles/new.html
{% extends 'base.html' %}
{% block content %}
<h1>NEW</h1>

<form action="{% url 'articles:create' %}" method="POST">
  {% csrf_token %}
  <label for="title">TITLE: </label>
  <input type="text" id="title" name="title"><br>
  <!-- form >> request >>  -->
  <label for="content">CONTENT: </label>
  <textarea name="content" id="content" cols="30" rows="10"></textarea><br>
  <input type="submit" value="작성">
</form>

<a href="{% url 'articles:index' %}">[메인 페이지로 이동]</a>
{% endblock content %}

django/0902/articles/templates/articles/update.html
{% extends 'base.html' %}

{% block content %}
<h1>Update Success.</h1>
{% endblock content %}